name: Release new FEM on Colab package

on:
  workflow_dispatch:
    inputs:
      library:
        description: "Library to build"

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    steps:
      - name: Store the current date and time
        id: date_time
        run: echo "::set-output name=date_time::$(date '+%Y%m%d-%H%M%S')"
      - name: Install git
        run: |
          apt update
          apt install -y -qq git
      - uses: actions/checkout@v1
      - name: Compute short SHA of the commit
        id: sha_short
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Print release name, release date and git commit sha
        run: echo "${{ github.event.inputs.library }} ${{ steps.date_time.outputs.date_time }} ${{ steps.sha_short.outputs.sha_short }}"
      - name: Setup Colab base image
        id: colab
        run: |
          source ./colab/install.sh
          echo "::set-output name=path::${PATH}"
          echo "::set-output name=pythonpath::${PYTHONPATH}"
          echo "::set-output name=install_prefix::${INSTALL_PREFIX}"
          echo "::set-output name=cppflags::${CPPFLAGS}"
          echo "::set-output name=ldflags::${LDFLAGS}"
        shell: bash
      - name: Build library
        run: |
          LIBRARY=${{ github.event.inputs.library }}
          [[ -f ${LIBRARY}/build.sh ]] && bash ${LIBRARY}/build.sh || true
        env:
          PATH: ${{ steps.colab.outputs.path }}
          PYTHONPATH: ${{ steps.colab.outputs.pythonpath }}
          INSTALL_PREFIX: ${{ steps.colab.outputs.install_prefix }}
          CPPFLAGS: ${{ steps.colab.outputs.cppflags }}
          LDFLAGS: ${{ steps.colab.outputs.ldflags }}
        shell: bash
      - name: Test library
        run: |
          LIBRARY=${{ github.event.inputs.library }}
          LIBRARY_CAPITAL=$(echo ${LIBRARY} | tr a-z A-Z)
          declare -x "${LIBRARY_CAPITAL}_ARCHIVE_PATH"="$PWD/${LIBRARY}-install.tar.gz"
          bash ${LIBRARY}/install.sh
          pytest ${LIBRARY}/test.ipynb
        env:
          PATH: ${{ steps.colab.outputs.path }}
          PYTHONPATH: ${{ steps.colab.outputs.pythonpath }}
        shell: bash
      - name: Force loading libstdc++.so from newest gcc
        run: |
          ERROR_LIBRARIES=($(find /usr/local -name '*\.so' -exec bash -c 'ldd $0 | grep libstdc++.so.6 1>/dev/null 2>/dev/null && echo $0' {} \;))
          for ERROR_LIBRARY in "${ERROR_LIBRARIES[@]}"; do
            echo "Patching $ERROR_LIBRARY"
            patchelf --replace-needed libstdc++.so.6 /usr/lib/gcc/x86_64-linux-gnu/11/libstdc++.so $ERROR_LIBRARY
          done
        shell: bash
      - name: Check if a release is needed
        id: check_release
        run: |
          LIBRARY=${{ github.event.inputs.library }}
          LIBRARY_CAPITAL=$(echo ${LIBRARY} | tr a-z A-Z)
          declare "${LIBRARY_CAPITAL}_ARCHIVE_PATH"="$PWD/${LIBRARY}-install.tar.gz"
          PATH_TO_CHECK=${LIBRARY_CAPITAL}_ARCHIVE_PATH
          [[ -f "${!PATH_TO_CHECK}" ]] && NEEDS_RELEASE="yes" || NEEDS_RELEASE="no"
          echo "::set-output name=needs_release::${NEEDS_RELEASE}"
        shell: bash
      - name: Add release to repository
        if: steps.check_release.outputs.needs_release == 'yes'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          automatic_release_tag: ${{ github.event.inputs.library }}-${{ steps.date_time.outputs.date_time }}-${{ steps.sha_short.outputs.sha_short }}
          title: "${{ github.event.inputs.library }} ${{ steps.date_time.outputs.date_time }} ${{ steps.sha_short.outputs.sha_short }}"
          files: ${{ github.event.inputs.library }}-install.tar.gz
      - name: Prepare release file for website
        run: |
          LIBRARY=${{ github.event.inputs.library }}
          LIBRARY_CAPITAL=$(echo ${LIBRARY} | tr a-z A-Z)
          DATETIME=${{ steps.date_time.outputs.date_time }}
          SHA_SHORT=${{ steps.sha_short.outputs.sha_short }}
          mkdir -p _build/html/releases
          cp ./${LIBRARY}/install.sh _build/html/releases/${LIBRARY}-install.sh
          sed -i "s|${LIBRARY_CAPITAL}_ARCHIVE_PATH_IN|https://github.com/fem-on-colab/fem-on-colab/releases/download/${LIBRARY}-${DATETIME}-${SHA_SHORT}/${LIBRARY}-install.tar.gz|g" _build/html/releases/${LIBRARY}-install.sh
        shell: bash
      - name: Upload release file to website
        if: github.repository == 'fem-on-colab/fem-on-colab'
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          external_repository: fem-on-colab/fem-on-colab.github.io
          publish_dir: _build/html
          keep_files: true
          user_name: 'GitHub Actions'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
