name: Release new FEM on Colab package

on:
  workflow_dispatch:
    inputs:
      library:
        description: "Library to build"

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    steps:
      - name: Store the current date and time
        id: date_time
        run: echo "::set-output name=date_time::$(date '+%Y%m%d-%H%M%S')"
      - name: Install git
        run: |
          apt update
          apt install -y -qq git
      - uses: actions/checkout@v1
      - name: Compute short SHA of the commit
        id: sha_short
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Print release name, release date and git commit sha
        run: echo "${{ github.event.inputs.library }} ${{ steps.date_time.outputs.date_time }} ${{ steps.sha_short.outputs.sha_short }}"
      - name: Setup Colab base image
        run: |
          source ./colab/install.sh
          echo "$PATH" > $GITHUB_PATH
          echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV
          echo "LD_PRELOAD=$LD_PRELOAD" >> $GITHUB_ENV
          echo "INSTALL_PREFIX=$INSTALL_PREFIX" >> $GITHUB_ENV
        shell: bash
      - name: Build library
        run: |
          bash ./${{ github.event.inputs.library }}/build.sh
      - name: Test library
        run: |
          LIBRARY_CAPITAL=$(echo ${{ github.event.inputs.library }} | tr a-z A-Z)
          declare -x "${LIBRARY_CAPITAL}_ARCHIVE_PATH"="$PWD/${{ github.event.inputs.library }}-install.tar.gz"
          bash ./${{ github.event.inputs.library }}/install.sh
          pytest ./${{ github.event.inputs.library }}/test.ipynb
        shell: bash
      - name: Add release to repository
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          automatic_release_tag: ${{ github.event.inputs.library }}-${{ steps.date_time.outputs.date_time }}-${{ steps.sha_short.outputs.sha_short }}
          title: "${{ github.event.inputs.library }} ${{ steps.date_time.outputs.date_time }} ${{ steps.sha_short.outputs.sha_short }}"
          files: ${{ github.event.inputs.library }}-install.tar.gz
      - name: Prepare release file for website
        run: |
          LIBRARY=${{ github.event.inputs.library }}
          DATETIME=${{ steps.date_time.outputs.date_time }}
          SHA_SHORT=${{ steps.sha_short.outputs.sha_short }}
          mkdir -p _build/html/releases
          cp ./${LIBRARY}/install.sh _build/html/releases/${LIBRARY}-install.sh
          sed -i "s|ARCHIVE_PATH_IN|https://github.com/fem-on-colab/fem-on-colab/releases/download/${LIBRARY}-${DATETIME}-${SHA_SHORT}/${LIBRARY}-install.tar.gz|g" _build/html/releases/${LIBRARY}-install.sh
      - name: Upload release file to website
        if: github.repository == 'fem-on-colab/fem-on-colab'
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          external_repository: fem-on-colab/fem-on-colab.github.io
          publish_dir: _build/html
          keep_files: true
          user_name: 'GitHub Actions'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
