name: Scheduled release of all FEM on Colab packages

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
    inputs:
      library:
        description: "Library to build and test."

jobs:
  # Mock build & test
  build_mock:
    if: github.repository == 'fem-on-colab/fem-on-colab' && (github.event_name == 'schedule' || github.event.inputs.library == 'mock')
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@main
    with:
      library: "mock"
      task: "build"
      args: ""
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

  test_mock:
    needs: [build_mock]
    uses: fem-on-colab/fem-on-colab/.github/workflows/release.yml@main
    with:
      library: "mock"
      task: "test"
      args: ""

  # Warn if scheduled workflow is about to be disabled
  warn:
    runs-on: ubuntu-latest
    if: github.repository == 'fem-on-colab/fem-on-colab' && github.ref == 'refs/heads/main' && github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v2
      - name: Warn if scheduled workflow is about to be disabled
        uses: fem-on-colab/warn-workflow-about-to-be-disabled-action@main
        with:
          workflow-filename: schedule_all.yml
          days-elapsed: 28
